services:
  temporal:
    image: temporalio/server:latest
    ports:
      - "7233:7233"
    environment:
      - DB=cassandra
      - DB_PORT=9042
      - DEFAULT_NAMESPACE=default
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./config/docker.yaml:/etc/temporal/config/docker.yaml
    networks:
      - temporal-network

  cassandra:
    image: cassandra:3.11
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=TemporalCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces'"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - temporal-network

networks:
  temporal-network:
    name: temporal-network
